name: Deploy AWS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.

      - name: Install libs
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t emozart/desafio-avanade-natura:v1 .

      - name: Publish image on DockerHub
        run: docker push emozart/desafio-avanade-natura:v1

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from DockerHub
        run: docker pull emozart/desafio-avanade-natura:v1

      - name: Delete old container
        run: docker rm -f desafio-avanade-natura

      - name: Run Docker Container
        run: docker run -d -p 80:3000 --name desafio-avanade-natura emozart/desafio-avanade-natura:v1 sh -c "npm run start"